### ISSUE TITLE
hashie.py: Dependency hcxpcaptool is deprecated (replaced with hcxpcapngtool)

### ISSUE THREAD

**Issue by Daviey** [evilsocket/pwnagotchi-plugins-contrib#23]
According to the [changelog](https://github.com/ZerBea/hcxtools/blob/master/changelog#L25) for hcxtools, hcxpcaptool has been deprecated and replaced with hcxpcapngtool.  It is currently not possible to build hcxpcaptool from either the most recent upstream release or git master.

**Comment by jLynx** [comment]
Fixed in https://github.com/evilsocket/pwnagotchi-plugins-contrib/pull/26
